In [0]:
import tensorflow as tf

In [0]:
import pandas as pd
import numpy as np

In [33]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

#1. Read the dataset

In [0]:
data_df = pd.read_csv('/content/drive/My Drive/PGAIML/bank.csv')

In [35]:
data_df.shape

(10000, 14)

1. Read the dataset

In [51]:
data_df.sample(n=5)

      RowNumber  CustomerId    Surname  ...  IsActiveMember EstimatedSalary Exited
5871       5872    15709920      Burke  ...               0        50774.81      1
6400       6401    15585907    Collier  ...               0       179066.58      0
6133       6134    15620735    Chiganu  ...               0        69011.66      0
9120       9121    15796838    Chibugo  ...               1        85148.78      0
3644       3645    15626233  Onyekachi  ...               1       151978.36      0

[5 rows x 14 columns]

###2. Drop the columns which are unique for all users like IDs (5 points)
###3. Distinguish the feature and target set (5 points)

In [0]:
# Removing unwanted columns and keeping only important features 
# Credit Score through Estimated Salary
X = data_df.iloc[:,3:13] 

# Exited -  Target variable
y = data_df.iloc[:, 13]

In [38]:
X.head()

   CreditScore Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          619    France  Female  ...          1               1        101348.88
1          608     Spain  Female  ...          0               1        112542.58
2          502    France  Female  ...          1               0        113931.57
3          699    France  Female  ...          0               0         93826.63
4          850     Spain  Female  ...          1               1         79084.10

[5 rows x 10 columns]

In [39]:
#Label encoding for categorical data

from sklearn.preprocessing import LabelEncoder
labelencoder_x = LabelEncoder()
# encoding for Geography
X.iloc[:, 1] = labelencoder_x.fit_transform(X.iloc[:, 1])
X.head()

   CreditScore  Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          619          0  Female  ...          1               1        101348.88
1          608          2  Female  ...          0               1        112542.58
2          502          0  Female  ...          1               0        113931.57
3          699          0  Female  ...          0               0         93826.63
4          850          2  Female  ...          1               1         79084.10

[5 rows x 10 columns]

In [40]:
#label encoding Gender

labelencoder_x_2 = LabelEncoder()
X.iloc[:, 2] = labelencoder_x_2.fit_transform(X.iloc[:, 2])
X.head()

   CreditScore  Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          619          0       0  ...          1               1        101348.88
1          608          2       0  ...          0               1        112542.58
2          502          0       0  ...          1               0        113931.57
3          699          0       0  ...          0               0         93826.63
4          850          2       0  ...          1               1         79084.10

[5 rows x 10 columns]

In [41]:
#Using Onehot encoding

from keras.utils import to_categorical
encoded = pd.DataFrame(to_categorical(X.iloc[:, 1]))

X = pd.concat([encoded, X], axis = 1)
X.head()

     0    1    2  ...  HasCrCard  IsActiveMember  EstimatedSalary
0  1.0  0.0  0.0  ...          1               1        101348.88
1  0.0  0.0  1.0  ...          0               1        112542.58
2  1.0  0.0  0.0  ...          1               0        113931.57
3  1.0  0.0  0.0  ...          0               0         93826.63
4  0.0  0.0  1.0  ...          1               1         79084.10

[5 rows x 13 columns]

In [42]:
#Dropping the existing "Geography" field from dataframe, and one of the onehotcoded columns

X = X.drop(['Geography', 0], axis = 1)
X.head()

     1    2  CreditScore  ...  HasCrCard  IsActiveMember  EstimatedSalary
0  0.0  0.0          619  ...          1               1        101348.88
1  0.0  1.0          608  ...          0               1        112542.58
2  0.0  0.0          502  ...          1               0        113931.57
3  0.0  0.0          699  ...          0               0         93826.63
4  0.0  1.0          850  ...          1               1         79084.10

[5 rows x 11 columns]

### 4. Divide the data set into Train and test sets
### 5. Normalize the train and test data (5 points)

In [0]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

# Feature Scaling using StandardScaler
sc=StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

###6. Initialize & build the model (10 points)**

In [44]:
import keras
from keras.models import Sequential
from keras.layers import Dense

model = Sequential()
#input_dim: 11
#output_dim: (11+1)÷2=6
#init --> initialize weights according to uniform distribution
#input_dim is required for the first hidden layer, as it is the first starting point. --> number of nodes.
#output_dim --> number of nodes of the hidden layer
model.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu', input_dim = 11))


#input_dim --> removing it as it already known what to expect
model.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu'))


#the output layer
#output_dim should be 1, as output is binary outcome, and activation should be 'sigmoid'
#If dependent variables have more than two categories, use activation = 'softmax'
model.add(Dense(output_dim = 1, init = 'uniform', activation = 'sigmoid'))


#compile the model --> backpropagation -> gradient descent
model.compile(optimizer = 'adam', loss = "binary_crossentropy", metrics = ['accuracy'])

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:6: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform")`

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:12: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  if sys.path[0] == '':
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:16: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  app.launch_new_instance()

###7.Optimize the model (Optional)

In [66]:
model.fit(X_train, y_train, batch_size = 10, nb_epoch = 25)

Epoch 1/25
1220/7000 [====>.........................] - ETA: 0s - loss: 0.4037 - acc: 0.8311

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  """Entry point for launching an IPython kernel.

7000/7000 [==============================] - 1s 127us/step - loss: 0.3742 - acc: 0.8441
Epoch 2/25
7000/7000 [==============================] - 1s 147us/step - loss: 0.3682 - acc: 0.8476
Epoch 3/25
7000/7000 [==============================] - 1s 127us/step - loss: 0.3637 - acc: 0.8473
Epoch 4/25
7000/7000 [==============================] - 1s 120us/step - loss: 0.3603 - acc: 0.8511
Epoch 5/25
7000/7000 [==============================] - 1s 118us/step - loss: 0.3563 - acc: 0.8580
Epoch 6/25
7000/7000 [==============================] - 1s 120us/step - loss: 0.3542 - acc: 0.8559
Epoch 7/25
7000/7000 [==============================] - 1s 119us/step - loss: 0.3520 - acc: 0.8576
Epoch 8/25
7000/7000 [==============================] - 1s 120us/step - loss: 0.3511 - acc: 0.8567
Epoch 9/25
7000/7000 [==============================] - 1s 119us/step - loss: 0.3498 - acc: 0.8587
Epoch 10/25
7000/7000 [==============================] - 1s 119us/step - loss: 0.3493 - acc: 0.8587
Epoch 11/25
7000/7000 [==============================] - 1s 120us/step - loss: 0.3493 - acc: 0.8594
Epoch 12/25
7000/7000 [==============================] - 1s 119us/step - loss: 0.3482 - acc: 0.8597
Epoch 13/25
7000/7000 [==============================] - 1s 111us/step - loss: 0.3472 - acc: 0.8616
Epoch 14/25
7000/7000 [==============================] - 1s 108us/step - loss: 0.3475 - acc: 0.8607
Epoch 15/25
7000/7000 [==============================] - 1s 111us/step - loss: 0.3468 - acc: 0.8600
Epoch 16/25
7000/7000 [==============================] - 1s 111us/step - loss: 0.3467 - acc: 0.8611
Epoch 17/25
7000/7000 [==============================] - 1s 112us/step - loss: 0.3462 - acc: 0.8614
Epoch 18/25
7000/7000 [==============================] - 1s 110us/step - loss: 0.3464 - acc: 0.8614
Epoch 19/25
7000/7000 [==============================] - 1s 109us/step - loss: 0.3460 - acc: 0.8617
Epoch 20/25
7000/7000 [==============================] - 1s 109us/step - loss: 0.3453 - acc: 0.8630
Epoch 21/25
7000/7000 [==============================] - 1s 110us/step - loss: 0.3447 - acc: 0.8639
Epoch 22/25
7000/7000 [==============================] - 1s 111us/step - loss: 0.3462 - acc: 0.8604
Epoch 23/25
7000/7000 [==============================] - 1s 108us/step - loss: 0.3455 - acc: 0.8613
Epoch 24/25
7000/7000 [==============================] - 1s 111us/step - loss: 0.3455 - acc: 0.8636
Epoch 25/25
7000/7000 [==============================] - 1s 112us/step - loss: 0.3446 - acc: 0.8636

### 8. Predict the results using 0.5 as a threshold (Optional)

In [0]:
# predicting the results

y_pred = model.predict(X_test)
y_pred = (y_pred > 0.5) #to classify each probability into True or False to indicate whether they are likely to exit or not

In [68]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_7 (Dense)              (None, 6)                 72
_________________________________________________________________
dense_8 (Dense)              (None, 6)                 42
_________________________________________________________________
dense_9 (Dense)              (None, 1)                 7
=================================================================
Total params: 121
Trainable params: 121
Non-trainable params: 0
_________________________________________________________________

#2. Print the Accuracy score and confusion matrix (5 points)**

In [69]:

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print (cm, '\n\n\n', y_pred[:5, :])

[[2220  159]
 [ 280  341]]


 [[False]
 [False]
 [False]
 [False]
 [False]]

In [70]:
cm=metrics.classification_report(y_test,y_pred)
print(cm)

              precision    recall  f1-score   support

           0       0.89      0.93      0.91      2379
           1       0.68      0.55      0.61       621

    accuracy                           0.85      3000
   macro avg       0.79      0.74      0.76      3000
weighted avg       0.85      0.85      0.85      3000

In [71]:
print('Accuracy: ' , metrics.accuracy_score(y_test,y_pred))

Accuracy:  0.8536666666666667